name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    name: Build and deploy
    uses: health-education-england/.github/.github/workflows/build-gradle.yml@main
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}

